name: Build Windows EXE

on:
  push:
    branches:
      - main   # triggers on every push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller moviepy

      - name: Build EXE with custom icon
        run: |
          pyinstaller --onefile --noconsole --icon=ff.ico main.py
          # replace "main.py" with your script
          # replace "ff.ico" with your icon path

      - name: Create Release and Upload EXE
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: "build-${{ github.run_number }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.KEY }}
