name: Build Windows EXE

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main           # also run automatically on pushes to main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller moviepy

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --icon=app.ico main.py
          # replace "main.py" with your entry script

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*
